export const usersTableColumns = [
    {
        title: 'id-пользователя',
        dataIndex: 'id',
        data_type: 'string',
        is_sort: true,
        number_in_row: 2,
    },
    //     {
    //         title: 'Статус ',
    //         dataIndex: 'status',
    //         data_type: 'string',
    //         is_sort: true,
    //         number_in_row: 1,
    //     },
    //     {
    //         title: 'username',
    //         dataIndex: 'username',
    //         data_type: 'string',
    //         is_sort: true,
    //         number_in_row: 1,
    //     },
    {
        title: 'email',
        dataIndex: 'email',
        data_type: 'string',
        is_sort: true,
        number_in_row: 1,
    },
    //     {
    //         title: 'ИНН',
    //         dataIndex: 'org_inn',
    //         data_type: 'string',
    //         is_sort: true,
    //         number_in_row: 1,
    //     },
    //     {
    //         title: 'ОГРН',
    //         dataIndex: 'org_ogrn',
    //         data_type: 'string',
    //         is_sort: true,
    //         number_in_row: 1,
    //     },
    //     {
    //         title: 'Номер телефона',
    //         dataIndex: 'phone',
    //         data_type: 'string',
    //         is_sort: true,
    //         number_in_row: 1,
    //     },
];
